plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'eclipse'
    id 'maven-publish'
}

group = 'com.example.saga'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework:spring-framework-bom:6.1.8"
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.2.0"
    }
}

dependencies {

    api 'org.springframework:spring-context'
    api 'org.springframework:spring-aop'
    api 'org.springframework:spring-web'
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'org.aspectj:aspectjrt:1.9.22'
    api 'org.aspectj:aspectjweaver:1.9.22'

    api 'org.slf4j:slf4j-api:2.0.9'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'com.example.saga'
            artifactId = 'core-saga'
            version = '1.0.0'
        }
    }
}
